### PR TITLE
Add support for licenses that use a "COPYING" file

### PR DESCRIPTION
**Pull request by ptsouchlos**
Some projects like https://github.com/TartanLlama/expected use a `COPYING` file for their license. This adds support for this case.

### CODE REVIEW

**Review by TheLartians — CHANGES_REQUESTED** [review]
Makes sense, thanks for the PR! Could you run cmake-format on the code to fix styling issues?

**Comment by ptsouchlos** [comment]
Done! Let me know if there's anything else I missed.

**Review by TheLartians — APPROVED** [review]
Looks good, thanks for the changes!

**Comment by OlivierLDff** [comment]
If you are using `tl::expected` you might be interested in [my fork](https://github.com/OlivierLDff/expected) which work better with `add_subdirectory`
Have a nice day, and thanks for the PR!

**Pull request merged**
